### ISSUE TITLE
406 Error

### ISSUE THREAD

**Issue by Roxenyo** [datwalkerv/TubeConverterAPI#1]
Receiving {"status":406,"message":"Invalid link!"} error when using the example: https://tube-converter.vercel.app/mp3/zzcuRGc0ruQ

**Comment by datwalkerv** [comment]
This method don't work from now on, I need to rewrite the whole script.

**Comment by HavannaFR** [comment]
Same error for me, can't wait for it to be fixed :)

**Comment by datwalkerv** [comment]
I fixed it, it will be soon available. Much love <3

**Comment by datwalkerv** [comment]
Problem fixed

**Comment by HavannaFR** [comment]
> Problem fixed

Thanks for the update ! But I think there is still a problem, take for example your link which serves as an example: https://tube-converter.vercel.app/mp3/zzcuRGc0ruQ, the link works but the download links return "This download token is invalid."
